// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore'], function($, Backbone, _) {
    var InfoView, _ref;
    InfoView = (function(_super) {
      __extends(InfoView, _super);

      function InfoView() {
        _ref = InfoView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      InfoView.prototype.tagName = 'ul';

      InfoView.prototype.className = 'info';

      InfoView.prototype.template = _.template($('#infoTempl').html());

      InfoView.prototype.events = {
        'click #close': 'close',
        'click #edit': 'edit'
      };

      InfoView.prototype.close = function() {
        this.model.trigger('itemClicked');
        return this.remove();
      };

      InfoView.prototype.edit = function() {
        return this.model.trigger('editClicked', this.model);
      };

      InfoView.prototype.render = function() {
        this.$el.html(this.template(this.model.toJSON()));
        return this;
      };

      return InfoView;

    })(Backbone.View);
    return InfoView;
  });

}).call(this);

/*
//@ sourceMappingURL=InfoView.map
*/
