// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'UsersCollection', 'UsersView', 'InfoView', 'EditView'], function($, Backbone, UsersCollection, UsersView, InfoView, EditView) {
    var Router;
    Router = (function(_super) {
      __extends(Router, _super);

      Router.prototype.routes = {
        '': 'index',
        'info/:id': 'info',
        'edit/:id': 'edit'
      };

      Router.prototype.usersCollection = {};

      Router.prototype.Views = {
        usersView: null,
        infoView: null,
        editView: null
      };

      function Router(people) {
        Router.__super__.constructor.apply(this, arguments);
        this.usersCollection = new UsersCollection(people);
        Backbone.history.start();
        this.listenTo(this.usersCollection, 'itemClicked', this.itemClicked);
        this.listenTo(this.usersCollection, 'editClicked', this.editClicked);
      }

      Router.prototype.itemClicked = function(model) {
        var modelId;
        this.Views.usersView.deselect();
        if (model) {
          modelId = this.usersCollection.indexOf(model);
          return this.navigate("info/" + modelId, true);
        }
      };

      Router.prototype.editClicked = function(model) {
        var modelId;
        modelId = this.usersCollection.indexOf(model);
        return this.navigate("edit/" + modelId, true);
      };

      Router.prototype.index = function() {
        if (!this.Views.usersView) {
          this.Views.usersView = new UsersView({
            collection: this.usersCollection
          });
          return $("#users").append(this.Views.usersView.render().el);
        }
      };

      Router.prototype.info = function(id) {
        var model;
        if (!this.Views.usersView) {
          this.index();
        }
        model = this.usersCollection.at(id);
        this.Views.infoView = new InfoView({
          model: model
        });
        return $('#information').html(this.Views.infoView.render().el);
      };

      Router.prototype.edit = function(id) {
        var model;
        if (!this.Views.usersView) {
          this.index();
        }
        this.Views.infoView.remove();
        model = this.usersCollection.at(id);
        this.Views.editView = new EditView({
          model: model
        });
        return $('#information').html(this.Views.editView.render().el);
      };

      return Router;

    })(Backbone.Router);
    return Router;
  });

}).call(this);

/*
//@ sourceMappingURL=Router.map
*/
