// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'UserModel'], function(Backbone, UserModel) {
    var UsersCollection, _ref;
    UsersCollection = (function(_super) {
      __extends(UsersCollection, _super);

      function UsersCollection() {
        _ref = UsersCollection.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      UsersCollection.prototype.model = UserModel;

      return UsersCollection;

    })(Backbone.Collection);
    return UsersCollection;
  });

}).call(this);

/*
//@ sourceMappingURL=UserCollection.map
*/
