// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['backbone'], function(Backbone) {
  var UserModel, _ref;
  return UserModel = (function(_super) {
    __extends(UserModel, _super);

    function UserModel() {
      _ref = UserModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    UserModel.prototype.defaults = {
      name: '-',
      lastName: '-',
      gender: '-',
      age: 0,
      phoneNumber: '00000'
    };

    UserModel.prototype.validation = {
      name: {
        required: true,
        minLength: 2,
        msg: 'You must enter a name!'
      },
      lastName: {
        required: true,
        minLength: 2,
        msg: 'You must enter a last name!'
      },
      age: [
        {
          required: true,
          msg: 'You must enter an age!'
        }, {
          min: 1,
          msg: 'Age must be greater than 0!'
        }
      ],
      phoneNumber: {
        required: true,
        pattern: "^\\+?[0-9]{10,14}$",
        msg: 'Invalid phone number!'
      }
    };

    return UserModel;

  })(Backbone.Model);
});

/*
//@ sourceMappingURL=UserModel.map
*/
