// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'underscore', 'View'], function(Backbone, _, View) {
    var UsersView, _ref;
    UsersView = (function(_super) {
      __extends(UsersView, _super);

      function UsersView() {
        _ref = UsersView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      UsersView.prototype.tagName = 'ol';

      UsersView.prototype.deselect = function() {
        return this.$('.selected').removeClass('selected');
      };

      UsersView.prototype.render = function() {
        this.collection.each(function(user) {
          var userView;
          userView = new View({
            model: user
          });
          return this.$el.append(userView.render().el);
        }, this);
        return this;
      };

      return UsersView;

    })(Backbone.View);
    return UsersView;
  });

}).call(this);

/*
//@ sourceMappingURL=UsersView.map
*/
