// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore'], function($, Backbone, _) {
    var View;
    View = (function(_super) {
      __extends(View, _super);

      View.prototype.tagName = 'li';

      View.prototype.className = 'item';

      View.prototype.template = _.template($('#user').html());

      View.prototype.events = {
        'click': 'clicked'
      };

      function View() {
        View.__super__.constructor.apply(this, arguments);
        this.html = this.template(this.model.toJSON());
        this.model.on('change', this.repaint, this);
      }

      View.prototype.repaint = function() {
        this.$el.removeClass('selected');
        return this.render();
      };

      View.prototype.clicked = function() {
        this.model.trigger('itemClicked', this.model);
        return this.$el.addClass('selected');
      };

      View.prototype.render = function() {
        this.$el.html(this.template(this.model.toJSON()));
        return this;
      };

      return View;

    })(Backbone.View);
    return View;
  });

}).call(this);

/*
//@ sourceMappingURL=View.map
*/
